### ISSUE TITLE
Difference between Fortify and Jetstream

### ISSUE THREAD

**Issue by mai1237** [Kamona-WD/kui-laravel-fortify#2]
Is there difference between kui-laravel-fortify and kui-laravel-jetsrream?
CannI use the kui-laravel-fortify  version in jetstream installation?

**Comment by Kamona-WD** [comment]
kui-laravel-fortify will scaffold ui for [laravel/fortify](https://laravel.com/docs/9.x/fortify) without adding any new functionality related to the back-end, it is just ui for existing laravel/fortify routes because fortify is just a back-end without front-end. but [kui-laravel-jetsrream](https://github.com/Kamona-WD/kui-laravel-jetstream) will replace the ui that came with [laravel/jetstream](https://jetstream.laravel.com/2.x/introduction.html) already with another ui without adding any new back-end functionality.
so
use kui-laravel-fortify if you will use laravel/fortify to generate ui for laravel/fortify.
and kui-laravel-jetsrream if you will use laravel/jetstream and need different ui.
